ch18/learning_log/learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = "learning_logs"
urlpatterns = [
    # Home page
    path("", views.index, name="index"),
    # Page that shows all topics.
    path("topics/", views.topics, name="topics"),
    # Detail page for a single topic.
    path("topics/<int:topic_id>/", views.topic, name="topic"),
]

ch18/learning_log/learning_logs/views.py
from django.shortcuts import render

from .models import Topic


def index(request):
    """The home page for Learning Log."""
    return render(request, "learning_logs/index.html")


def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by("date_added")
    context = {"topics": topics}
    return render(request, "learning_logs/topics.html", context)


def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/topic.html", context)

ch18/learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %} {% block content %}
<p>Entries:</p>
<ul>
  {% for entry in entries %}
  <li>
    <p>{{entry.date_added|date:'M d, Y H:i'}}</p>
    <p>{{entry.text | linebreaks}}</p>
  </li>
  {% empty %}
  <li>There are no entries for the topic yet.</li>
  {% endfor %}
</ul>

{% endblock content %}

ch18/learning_log/learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %} {% block content %}

<p>Topics</p>
<ul>
  {% for topic in topics %}
  <li>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{topic.text}}</a>
  </li>
  {% empty %}
  <li>No topics have been added yet.</li>
  {% endfor %}
</ul>

{% endblock content %}